### ISSUE TITLE
cerbero bootstrap Fatal Error: Data dir not found

### ISSUE THREAD

**Issue by tausiq** [lubosz/cerbero#1]
Hello, 

I am trying to build GStreamer using Cerbero by following this guide. 

Steps I followed: 
1. Clone the latest master repo: http://cgit.freedesktop.org/gstreamer/cerbero/
2. Ran the command: 
   `echo "alias cerbero='~/git/cerbero/cerbero-uninstalled'" >> ~/.bashrc` 

3.Create and edit the file $HOME/.cerbero/cerbero.cbc 

```
import os 
from cerbero.config import Platform, Architecture, Distro 

packages_prefix = 'gstreamer-1.0' 
packager = 'GStreamer SDK packagers <packages@gstreamer.com>' 
prefix = "/opt/gstreamer-1.0" 

git_root = "http://cgit.freedesktop.org/gstreamer/cerbero/" 

# Uncomment to allow parallel builds 
# allow_parallel_build = True 

# Uncomment this to allow cross-building for another architecture 
# target_arch = Architecture.X86_64 
```
1. Go to the Cerbero directory and ran: sudo python setup.py install 
2. Ran: cerbero bootstrap 

Getting the following error: 

```
Traceback (most recent call last): 
  File "/usr/local/bin/cerbero", line 9, in <module>
    load_entry_point('cerbero==0.1.0', 'console_scripts', 'cerbero')() 
  File "/Library/Python/2.7/site-packages/cerbero-0.1.0-py2.7.egg/cerbero/main.py", line 130, in main 
    Main(sys.argv[1:]) 
  File "/Library/Python/2.7/site-packages/cerbero-0.1.0-py2.7.egg/cerbero/main.py", line 54, in __init__ 
    self.load_config() 
  File "/Library/Python/2.7/site-packages/cerbero-0.1.0-py2.7.egg/cerbero/main.py", line 98, in load_config 
    self.config.load(self.args.config) 
  File "/Library/Python/2.7/site-packages/cerbero-0.1.0-py2.7.egg/cerbero/config.py", line 110, in load 
    self.load_defaults() 
  File "/Library/Python/2.7/site-packages/cerbero-0.1.0-py2.7.egg/cerbero/config.py", line 308, in load_defaults 
    self.set_property('data_dir', self._find_data_dir()) 
  File "/Library/Python/2.7/site-packages/cerbero-0.1.0-py2.7.egg/cerbero/config.py", line 468, in _find_data_dir 
    raise FatalError("Data dir not found") 
cerbero.errors.FatalError: Fatal Error: Data dir not found 
```

I am running Mac OS X, Yosemite. 

Did I do something wrong? Any help is appreciated. 

Thank you.

**Comment by tausiq** [comment]
Found the solution: 
1. No need to create $HOME/.cerbero/cerbero.cbc (unless you would like to provide custom value) 
2. No need to run: sudo python setup.py install
3. Run: ./cerbero-uninstalled bootstrap
   or,
   ./cerbero-uninstalled -c config/cross-ios-universal.cbc bootstrap (for iOS cross compilation)  
4. Run: ./cerbero-uninstalled -c config/cross-ios-universal.cbc package gstreamer-1.0 (for iOS cross compilation)

**Comment by lubosz** [comment]
Apparently even when you install cerbero with setup.py, you need to run it in the cerbero dir, so it can find the data files. 

Please note that this is just my github clone and not the official place to find support.
Go to #gstreamer on freenode, the gstreamer mailing list or stackoverflow for further support.
