### ISSUE TITLE
Connecting cerbero to "repo sync" manifest

### ISSUE THREAD

**Issue by jhgorse** [lubosz/cerbero#2]
Hello,

Is there a way to have cerbero use a "repo sync" manifest.xml?

GStreamer provides a manifest.xml, such as this:
https://ci.gstreamer.net/job/cerbero-osx-x86-64-1010/1847/tagBuild/

Which allows one to download the exact repositories used to build the successful build. However, cerbero appears to ignore the other directories in the "repo init/sync" directory and just do its own thing inside of the cerbero directory.

**Comment by lubosz** [comment]
Please note that this is just my github clone and not the official place to find support.
Go to #gstreamer on freenode, gnome bugzilla, the gstreamer mailing list or stackoverflow for further support.
